services:

  mssql:
    build: docker/mssql
    ports:
      - 1433:1433

  dev:
    build: docker/dev
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mssql
